version: '3.8'

services:
  matomo:
    build: .
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - MATOMO_USERNAME=${MATOMO_USERNAME}
      - MATOMO_PASSWORD=${MATOMO_PASSWORD}
      - MATOMO_DATABASE_HOST=matomo_db
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=${MARIADB_USER}
      - MATOMO_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - BITNAMI_DEBUG=true
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'matomo_data:/bitnami/matomo'
    depends_on:
      - matomo_db

  matomo_db:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=bitnami_matomo
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local
