name: Automated Docker Build Main Push C1 Artifactory

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push-C1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - run: |
          sudo sh scripts/add-dod-cas.sh

      - uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2
        id: buildx
        with:
          config-inline: |
            [registry."${{ secrets.C1_REGISTRY }}"]
              ca=["/etc/ssl/certs/adoptium/cacerts"]
              http = false
              insecure = true

      - name: Get Matomo version
        id: matomo_version
        run: |
          matomoTag=$(grep "bitnami/matomo:" Dockerfile | cut -d ":" -f 2)
          echo "matomo_tag=${matomoTag}" >> $GITHUB_OUTPUT

      - name: Build and Load image into local Docker
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
        with:
          context: .
          push: false
          load: true
          tags: ${{ secrets.C1_REGISTRY}}/${{ secrets.C1_REPOSITORY }}:${{ steps.matomo_version.outputs.matomo_tag }}-${{ github.sha }}
          build-args: |
            BUILD=${{ github.sha }}

      - name: Login to Dev Artifactory Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        with:
          registry: ${{ secrets.C1_REGISTRY }}
          username: ${{ secrets.C1_ART_USERNAME }}
          password: ${{ secrets.C1_ARTIFACTORY_TOKEN }}

      - name: Push to Dev Artifactory, Tag and Push to Prod Artifactory
        env:
          IMAGE_TAG: ${{ steps.matomo_version.outputs.matomo_tag }}-${{ github.sha }}
          C1_REGISTRY: ${{ secrets.C1_REGISTRY }}
          C1_REPOSITORY: ${{ secrets.C1_REPOSITORY }}
        run: |
          docker push $C1_REGISTRY/$C1_REPOSITORY:$IMAGE_TAG
          docker tag $C1_REGISTRY/$C1_REPOSITORY:$IMAGE_TAG $C1_REGISTRY/dockerreadyforprod/portal/matomo:$IMAGE_TAG
          docker push $C1_REGISTRY/dockerreadyforprod/portal/matomo:$IMAGE_TAG
